---
- name: Installing Zabbix repository
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-3%2Bubuntu20.04_all.deb
    state: present
    dpkg_options: "force-confdef,force-confnew"
    force: yes
    force_apt_get: yes

- name: Installing Zabbix repository
  apt_repository:
    repo: deb http://repo.zabbix.com/zabbix/6.0/ubuntu {{ ansible_distribution_release }} main
    state: present
    filename: /etc/apt/sources.list.d/zabbix
