version: "3"
services:
       variable:
               image: $IMAGE1
               ports:
               - $PORTS
               deploy:
                mode: replicated
                replicas: 5

       java_application:
              container_name: java_app
              image: $IMAGE2
              depends_on:
              - database

       database:
               container_name: dbcontainer
               image: $IMAGE3
               environment:
               - MYSQL_ROOT_PASSWORD=password
               - MYSQL_USER=user
               - MYSQL_PASSWORD=password

