version: "1.26.0"
services:
       variable:
               container_name: task5extra
               image: variable:latest
               ports:
               - 80:80

       java_application:
              container_name: java_app
              image: openjdk:demo
              depends_on:
              - database

       database:
               container_name: DBContainer
               image: mysql
               ports:
               - "3306:3306"
               environment:
               - MYSQL_ROOT_PASSWORD=password
               - MYSQL_USER=user
               - MYSQL_PASSWORD=password
                 #- MY_SQL_DATABASE=demodb
