version: "3"
services:
       variable:
               container_name: task5extra
               image: $IMAGE1
               ports: $PORTS

       java_application:
              container_name: java_app
              image: $IMAGE2
              depends_on:
              - database

       database:
               container_name: dbcontainer
               image: $IMAGE3
               #ports:
                       #- "3306:3306"
               environment:
               - MYSQL_ROOT_PASSWORD=password
               - MYSQL_USER=user
               - MYSQL_PASSWORD=password
